use dioxus::prelude::*;
use std::path::PathBuf;
use std::sync::mpsc;

use diffusion_rs::{
    api::gen_img_with_progress,
    preset::{Preset, PresetBuilder},
};

use crate::components::button::Button;
use crate::components::input::Input;
use crate::components::textarea::Textarea;

#[derive(Clone, Debug, PartialEq)]
pub struct ImageData {
    pub name: String,
    pub bytes: Vec<u8>,
}

fn base64_encode(data: &[u8]) -> String {
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut result = String::with_capacity((data.len() + 2) / 3 * 4);
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = if chunk.len() > 1 { chunk[1] as u32 } else { 0 };
        let b2 = if chunk.len() > 2 { chunk[2] as u32 } else { 0 };
        let triple = (b0 << 16) | (b1 << 8) | b2;

        result.push(CHARSET[((triple >> 18) & 0x3F) as usize] as char);
        result.push(CHARSET[((triple >> 12) & 0x3F) as usize] as char);
        if chunk.len() > 1 {
            result.push(CHARSET[((triple >> 6) & 0x3F) as usize] as char);
        } else {
            result.push('=');
        }
        if chunk.len() > 2 {
            result.push(CHARSET[(triple & 0x3F) as usize] as char);
        } else {
            result.push('=');
        }
    }
    result
}

#[component]
pub fn NewChat(on_submit: Option<EventHandler<(String, Option<ImageData>)>>) -> Element {
    let mut text_input = use_signal(String::new);
    let mut attached_image = use_signal(|| None::<ImageData>);

    let mut progress_status = use_signal_sync(String::new);
    let mut is_generating = use_signal_sync(|| false);
    let mut generated_image = use_signal_sync(|| None::<String>);

    let handle_image_upload = move |evt: FormEvent| async move {
        let files = evt.files();
        if let Some(file) = files.first() {
            let file_name = file.name();
            if let Ok(bytes) = file.read_bytes().await {
                attached_image.set(Some(ImageData {
                    name: file_name,
                    bytes: bytes.to_vec(),
                }));
            }
        }
    };

    let handle_submit = move |_| {
        let text = text_input.read().clone();
        let image = attached_image.read().clone();

        if text.trim().is_empty() && image.is_none() {
            return;
        }

        if let Some(callback) = &on_submit {
            callback.call((text.clone(), image));
        }

        text_input.set(String::new());
        attached_image.set(None);

        is_generating.set(true);
        generated_image.set(None);
        progress_status.set("Starting image generation...".into());

        let (progress_tx, progress_rx) = mpsc::channel();
        let (result_tx, result_rx) = mpsc::channel::<Result<Vec<u8>, String>>();

        // Thread 1: Generation
        std::thread::spawn(move || {
            let (config, mut model_config) = PresetBuilder::default()
                .preset(Preset::SDTurbo)
                .prompt(text)
                .build()
                .unwrap();

            match gen_img_with_progress(&config, &mut model_config, progress_tx) {
                Ok(_) => {
                    // Look for default output filenames generated by diffusion_rs
                    let candidate_paths = [
                        PathBuf::from("output.png"),
                        PathBuf::from("output_0.png"),
                        PathBuf::from("output_00001_.png"),
                    ];

                    let mut loaded_bytes = None;
                    for path in &candidate_paths {
                        if let Ok(bytes) = std::fs::read(path) {
                            loaded_bytes = Some(bytes);
                            break;
                        }
                    }

                    if let Some(bytes) = loaded_bytes {
                        let _ = result_tx.send(Ok(bytes));
                    } else {
                        let _ = result_tx.send(Err("Generated image output file not found.".into()));
                    }
                }
                Err(err) => {
                    let _ = result_tx.send(Err(format!("{:?}", err)));
                }
            }
        });

        // Thread 2: Progress & Output Listener
        std::thread::spawn(move || {
            while let Ok(progress) = progress_rx.recv() {
                progress_status.set(format!("Generating... {:?}", progress));
            }

            if let Ok(res) = result_rx.recv() {
                match res {
                    Ok(bytes) => {
                        let data_url = format!("data:image/png;base64,{}", base64_encode(&bytes));
                        generated_image.set(Some(data_url));
                        progress_status.set("Generation complete!".into());
                    }
                    Err(err) => {
                        progress_status.set(format!("Generation failed: {}", err));
                    }
                }
            }

            is_generating.set(false);
        });
    };

    rsx! {
        div {
            class: "flex justify-center items-center h-full",
            flex_direction: "column",
            text_align: "center",
            h1 { "New Chat" }

            div {
                class: "flex justify-center items-center w-full",
                flex_direction: "row",
                gap: ".5rem",

                Input {
                    id: "image-upload",
                    r#type: "file",
                    accept: "image/*",
                    class: "hidden",
                    onchange: handle_image_upload,
                }

                label {
                    r#for: "image-upload",
                    class: "cursor-pointer inline-flex items-center justify-center p-2 rounded-md border border-input bg-background hover:bg-accent hover:text-accent-foreground",
                    svg {
                        xmlns: "http://www.w3.org/2000/svg",
                        width: "20",
                        height: "20",
                        view_box: "0 0 24 24",
                        fill: "none",
                        stroke: "currentColor",
                        stroke_width: "2",
                        stroke_linecap: "round",
                        stroke_linejoin: "round",
                        path { d: "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" }
                        polyline { points: "17 8 12 3 7 8" }
                        line {
                            x1: "12",
                            y1: "3",
                            x2: "12",
                            y2: "15",
                        }
                    }
                }

                Textarea {
                    placeholder: "Type a prompt or message...",
                    value: "{text_input}",
                    oninput: move |evt: FormEvent| text_input.set(evt.value()),
                }

                Button { onclick: handle_submit, disabled: "{is_generating}",
                    svg {
                        xmlns: "http://www.w3.org/2000/svg",
                        width: "20",
                        height: "20",
                        view_box: "0 0 24 24",
                        fill: "none",
                        stroke: "currentColor",
                        stroke_width: "2",
                        stroke_linecap: "round",
                        stroke_linejoin: "round",
                        path { d: "m22 2-7 20-4-9-9-4Z" }
                        path { d: "M22 2 11 13" }
                    }
                }
            }

            if !progress_status.read().is_empty() {
                p { class: "mt-4 text-sm text-gray-400 animate-pulse", "{progress_status}" }
            }

            if let Some(img_url) = generated_image.read().as_ref() {
                div { class: "mt-6 max-w-md rounded-lg overflow-hidden border border-input shadow-md",
                    img {
                        src: "{img_url}",
                        alt: "Generated Output",
                        class: "w-full h-auto object-cover",
                    }
                }
            }
        }
    }
}